name: graphenv
channels:
  - conda-forge
  - defaults
dependencies:
  - gym
  - pytest
  - tensorflow
  - networkx
  - pip
  - pip:
    - nfp >= 0.3.11
    - "ray[tune,rllib]"
    - torch
    - torchaudio
    - torchvision
