name: Run Tests

on:
  push:
    branches:
      - "main"
    tags:
      - '*'
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]

    steps:
      -
        uses: actions/checkout@v1
      -
        name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a
      - 
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: devtools/conda-envs/environment.yml
          channels: conda-forge,defaults
          activate-environment: test
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      -
        name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          conda list
      -
        name: Run tests
        shell: bash -l {0}        
        run: pytest -v tests/